"""Migrators for the PUT_DOWN_LABWARE schema.

.. note:: Generated by Claude Opus 5.
"""

from ...registry import Migrator, RawData


def migrate_v1_to_v2(data: RawData) -> RawData:
    """Migrate a PUT_DOWN_LABWARE command from schema version 1 to 2.

    .. note:: Generated by Claude Opus 5.
    """
    # v2 only widens the `holder` union with ModuleId; every v1 holder still validates.
    retval = {
        **data,
    }
    retval["schema_version"] = 2
    return retval


MIGRATORS: dict[int, Migrator] = {
    2: migrate_v1_to_v2,
}
