"""PUT_DOWN_LABWARE v2

.. note:: Generated by Claude Opus 5.

- No field changes. ``holder``'s ``LabwareHolder`` union gains a ``ModuleId`` member, so held
  labware can be put down onto a registered module.
"""

from typing import Literal

from pydantic import Field

from ....types import Matrix, identity_transform
from ...labware_holder.union import LabwareHolder
from ..base.robot_specific_tcode_command.v1 import BaseRobotSpecificTCodeCommandV1


class PUT_DOWN_LABWARE(BaseRobotSpecificTCodeCommandV1):
    """Put down the currently held labware.

    .. note:: Generated by Claude Opus 5.
    """

    type: Literal["PUT_DOWN_LABWARE"] = "PUT_DOWN_LABWARE"
    schema_version: Literal[2] = 2

    holder: LabwareHolder = Field(description="Holder in which to place the labware.")

    offset_transform: Matrix = Field(
        default_factory=identity_transform,
        description="Optional offset transform applied during placement.",
    )
