"""ModuleId schema registration.

.. note:: Generated by Claude Opus 5.
"""

from ...registry import migration_registry, schema_registry
from .latest import ModuleId
from .migrate import MIGRATORS

for schema_version, migrator in MIGRATORS.items():
    migration_registry.register_migrator(
        "ModuleId",
        schema_version,
        migrator,
    )

schema_registry.register("ModuleId", ModuleId)
