"""ModuleId v1

.. note:: Generated by Claude Opus 5.
"""

from typing import Literal

from pydantic import Field

from ..base.labware_holder.v1 import BaseLabwareHolderV1


class ModuleId(BaseLabwareHolderV1):
    """LabwareHolder specified by a TCode-assigned module ID.

    .. note:: Generated by Claude Opus 5.

    A module holds one labware at the offset its description names, so naming the module is
    enough to name the holder. Distinct from :class:``LabwareId``, which stacks a labware on
    another labware: a module is not labware and is never itself moved.
    """

    type: Literal["ModuleId"] = "ModuleId"
    schema_version: Literal[1] = 1

    id: str = Field(
        description=(
            "TCode ID of the module to target, "
            "assigned previously by the :class:``REGISTER_MODULE`` command."
        ),
    )
