"""REGISTER_MODULE schema registration.

.. note:: Generated by Claude Opus 5.
"""

from ...registry import migration_registry, schema_registry
from .latest import REGISTER_MODULE
from .migrate import MIGRATORS

for schema_version, migrator in MIGRATORS.items():
    migration_registry.register_migrator(
        "REGISTER_MODULE",
        schema_version,
        migrator,
    )

schema_registry.register("REGISTER_MODULE", REGISTER_MODULE)
