"""Migrators for the REGISTER_MODULE schema.

.. note:: Generated by Claude Opus 5.
"""

from ...registry import Migrator, RawData

#: Fields a ``ModuleDescription`` requires that a ``ModuleDescriptor`` leaves optional. A legacy
#: payload that omits any of them describes a module only partially, which v1 permitted because
#: the remainder was to be resolved against the fleet. Nothing resolves a module, so there is
#: nowhere for the missing values to come from.
_REQUIRED_DESCRIPTION_FIELDS = (
    "x_length",
    "y_length",
    "z_length",
    "pinchable",
    "holder_transform",
    "supports_liftable_labware",
)


def migrate_v1_to_v2(data: RawData) -> RawData:
    """Migrate a REGISTER_MODULE command from schema version 1 to 2.

    .. note:: Generated by Claude Opus 5.

    v1 is the rename target for ``ADD_MODULE``, which carried a ``ModuleDescriptor`` on the
    assumption that a module would be matched against the fleet the way a robot or a labware
    is. It is not: a module is built from what the command supplies. v2 therefore takes a
    fully-specified ``ModuleDescription`` under ``description``.

    A descriptor that happens to specify every field migrates by renaming the key. One that
    does not cannot be completed by any means available here, so this migrator raises and
    names the fields it would have had to invent.
    """
    if "descriptor" not in data:
        raise ValueError(
            "Cannot migrate REGISTER_MODULE v1 to v2: the payload carries no 'descriptor'."
        )
    descriptor = data["descriptor"]
    missing = [
        field
        for field in _REQUIRED_DESCRIPTION_FIELDS
        if not isinstance(descriptor, dict) or descriptor.get(field) is None
    ]
    if missing:
        raise ValueError(
            "Cannot migrate REGISTER_MODULE v1 to v2 automatically: v2 takes a full "
            f"ModuleDescription, and this descriptor omits {', '.join(missing)}. Modules are "
            "never resolved against the fleet, so these have no source other than the command "
            "itself; supply them and re-issue the command."
        )
    retval = {key: value for key, value in data.items() if key != "descriptor"}
    retval["description"] = descriptor
    retval["schema_version"] = 2
    return retval


MIGRATORS: dict[int, Migrator] = {
    2: migrate_v1_to_v2,
}
