"""REGISTER_MODULE v1

.. note:: Generated by Claude Opus 5.

This version exists only as the rename target for ``ADD_MODULE`` v1, shipped in tcode-api
v1.50.0. Its shape is identical to that command's, down to the ``descriptor`` field; the
rename is recorded in ``APIHistoryLog.migrations`` and the field change is carried by the
v1 -> v2 migrator. Nothing constructs this class directly: ``latest.py`` points at v2, and
v1 payloads reach it only while being migrated.
"""

from typing import Annotated, Literal

from pydantic import Field

from ...descriptions.labware.module.v1 import ModuleDescriptor
from ...location.location_as_labware_holder.v1 import LocationAsLabwareHolder
from ...location.location_relative_to_robot.v1 import LocationRelativeToRobot
from ..base.tcode_command.v1 import BaseTCodeCommandV1

ModuleLocation = Annotated[
    LocationAsLabwareHolder | LocationRelativeToRobot,
    Field(
        discriminator="type",
        description=(
            "Where the module sits. A LocationAsLabwareHolder places it in a deck slot, so it "
            "can be moved between slots like any other labware. A LocationRelativeToRobot "
            "fixes it at a pose relative to the robot's root node, for modules that are bolted "
            "down and never moved."
        ),
    ),
]


class REGISTER_MODULE(BaseTCodeCommandV1):
    """Register a module and assign it the given id.

    .. note:: Generated by Claude Opus 5.

    :raises ValidatorError: ``ValidatorErrorCode.ID_EXISTS`` if ``id`` is already registered.
    """

    type: Literal["REGISTER_MODULE"] = "REGISTER_MODULE"
    schema_version: Literal[1] = 1

    id: str = Field(
        description=(
            "Identifier to assign to the resolved module. "
            "This id is used in subsequent commands to reference this module."
        )
    )
    descriptor: ModuleDescriptor = Field(
        description="Minimal descriptor of the desired module; resolved on the fleet."
    )
    location: ModuleLocation
