"""REGISTER_MODULE v2

.. note:: Generated by Claude Opus 5.

- ``descriptor: ModuleDescriptor`` becomes ``description: ModuleDescription``.

A module is not searched for on the fleet, so there is nothing for a partial descriptor to
resolve against. Taking a full description instead makes that explicit in the schema: the
command builds the module from what it is given and binds the id to the result, the way
``CREATE_LABWARE`` builds labware from a description rather than the way ``ADD_LABWARE``
matches a descriptor against hardware already present.
"""

from typing import Annotated, Literal

from pydantic import Field

from ...descriptions.labware.module.v1 import ModuleDescription
from ...location.location_as_labware_holder.v1 import LocationAsLabwareHolder
from ...location.location_relative_to_robot.v1 import LocationRelativeToRobot
from ..base.tcode_command.v1 import BaseTCodeCommandV1

ModuleLocation = Annotated[
    LocationAsLabwareHolder | LocationRelativeToRobot,
    Field(
        discriminator="type",
        description=(
            "Where the module sits. A LocationAsLabwareHolder places it in a deck slot, so it "
            "can be moved between slots like any other labware. A LocationRelativeToRobot "
            "fixes it at a pose relative to the robot's root node, for modules that are bolted "
            "down and never moved."
        ),
    ),
]


class REGISTER_MODULE(BaseTCodeCommandV1):
    """Create a module from its description and assign it the given id.

    .. note:: Generated by Claude Opus 5.

    A module is a deck-side device that both holds labware at an offset pose and accepts
    commands of its own. Registering it gives it an execution queue, so work addressed to the
    module is ordered against the module's other work rather than against a robot's. Use
    ``depends_on`` and ``sync_group`` on the schedule envelope to order module work against
    robot motion.

    No resolution takes place. Unlike ``ADD_ROBOT`` or ``ADD_LABWARE``, nothing on the fleet is
    searched: the description fully specifies the module, and the id is bound to it directly.

    :raises ValidatorError: ``ValidatorErrorCode.ID_EXISTS`` if ``id`` is already registered.
    """

    type: Literal["REGISTER_MODULE"] = "REGISTER_MODULE"
    schema_version: Literal[2] = 2

    id: str = Field(
        description=(
            "Identifier to assign to the module. "
            "This id is used in subsequent commands to reference this module."
        )
    )
    description: ModuleDescription = Field(description="Full description of the module to create.")
    location: ModuleLocation
